export { default as Hero } from './hero';
export { default as Auth } from './auth';
export { default as Sign } from './sign';
export { default as Forgot } from './forgot';
export { default as Home } from './home';
export { default as Loading } from './loading';
export { default as Upload } from './upload';
export { default as NotFound } from './notfound';
export { default as CameraCapture } from './capture';
